In [24]:
import pandas as pd
import numpy as np
star_wars = pd.read_csv("star_wars.csv", encoding="ISO-8859-1")
star_wars = star_wars[pd.notnull(star_wars["RespondentID"])]
star_wars.head()

,RespondentID,Have you seen any of the 6 films in the Star Wars franchise?,Do you consider yourself to be a fan of the Star Wars film franchise?,Which of the following Star Wars films have you seen? Please select all that apply.,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.,...,Unnamed: 28,Which character shot first?,Are you familiar with the Expanded Universe?,Do you consider yourself to be a fan of the Expanded Universe?ÂÃ¦,Do you consider yourself to be a fan of the Star Trek franchise?,Gender,Age,Household Income,Education,Location (Census Region)
1,3.292880e+09,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,3,...,Very favorably,I don't understand this question,Yes,No,No,Male,18-29,NaN,High school degree,South Atlantic
2,3.292880e+09,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,Yes,Male,18-29,"$0 - $24,999",Bachelor degree,West South Central
3,3.292765e+09,Yes,No,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,NaN,NaN,NaN,1,...,Unfamiliar (N/A),I don't understand this question,No,NaN,No,Male,18-29,"$0 - $24,999",High school degree,West North Central
4,3.292763e+09,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,5,...,Very favorably,I don't understand this question,No,NaN,Yes,Male,18-29,"$100,000 - $149,999",Some college or Associate degree,West North Central
5,3.292731e+09,Yes,Yes,Star Wars: Episode I The Phantom Menace,Star Wars: Episode II Attack of the Clones,Star Wars: Episode III Revenge of the Sith,Star Wars: Episode IV A New Hope,Star Wars: Episode V The Empire Strikes Back,Star Wars: Episode VI Return of the Jedi,5,...,Somewhat favorably,Greedo,Yes,No,No,Male,18-29,"$100,000 - $149,999",Some college or Associate degree,West North Central

In [25]:
yes_no = {
    "Yes": True,
    "No": False
}
star_wars["Have you seen any of the 6 films in the Star Wars franchise?"] = star_wars["Have you seen any of the 6 films in the Star Wars franchise?"].map(yes_no)
star_wars["Do you consider yourself to be a fan of the Star Wars film franchise?"] = star_wars["Do you consider yourself to be a fan of the Star Wars film franchise?"].map(yes_no)
print(star_wars["Do you consider yourself to be a fan of the Star Wars film franchise?"].head())

1     True
2      NaN
3    False
4     True
5     True
Name: Do you consider yourself to be a fan of the Star Wars film franchise?, dtype: object

In [26]:
cols = star_wars.columns[3:9]
#or col in star_wars:
    
star_map = {
    "Star Wars: Episode I  The Phantom Menace": True, 
    "Star Wars: Episode II  Attack of the Clones": True,
    "Star Wars: Episode III  Revenge of the Sith": True,
    "Star Wars: Episode IV  A New Hope": True,
    "Star Wars: Episode V The Empire Strikes Back": True,
    "Star Wars: Episode VI Return of the Jedi": True,
    np.nan: False
}

for col in cols:
    star_wars[col] = star_wars[col].map(star_map)

In [28]:

    
star_wars = star_wars.rename(columns={
        "Which of the following Star Wars films have you seen? Please select all that apply.": "seen_1",
        "Unnamed: 4": "seen_2",
        "Unnamed: 5": "seen_3",
        "Unnamed: 6": "seen_4",
        "Unnamed: 7": "seen_5",
        "Unnamed: 8": "seen_6"
        })
star_wars

,RespondentID,Have you seen any of the 6 films in the Star Wars franchise?,Do you consider yourself to be a fan of the Star Wars film franchise?,seen_1,seen_2,seen_3,seen_4,seen_5,seen_6,Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.,...,Unnamed: 28,Which character shot first?,Are you familiar with the Expanded Universe?,Do you consider yourself to be a fan of the Expanded Universe?ÂÃ¦,Do you consider yourself to be a fan of the Star Trek franchise?,Gender,Age,Household Income,Education,Location (Census Region)
1,3.292880e+09,True,True,True,True,True,True,True,True,3,...,Very favorably,I don't understand this question,Yes,No,No,Male,18-29,NaN,High school degree,South Atlantic
2,3.292880e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,Yes,Male,18-29,"$0 - $24,999",Bachelor degree,West South Central
3,3.292765e+09,True,False,True,True,True,False,False,False,1,...,Unfamiliar (N/A),I don't understand this question,No,NaN,No,Male,18-29,"$0 - $24,999",High school degree,West North Central
4,3.292763e+09,True,True,True,True,True,True,True,True,5,...,Very favorably,I don't understand this question,No,NaN,Yes,Male,18-29,"$100,000 - $149,999",Some college or Associate degree,West North Central
5,3.292731e+09,True,True,True,True,True,True,True,True,5,...,Somewhat favorably,Greedo,Yes,No,No,Male,18-29,"$100,000 - $149,999",Some college or Associate degree,West North Central
6,3.292719e+09,True,True,True,True,True,True,True,True,1,...,Very favorably,Han,Yes,No,Yes,Male,18-29,"$25,000 - $49,999",Bachelor degree,Middle Atlantic
7,3.292685e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,Han,Yes,No,No,Male,18-29,NaN,High school degree,East North Central
8,3.292664e+09,True,True,True,True,True,True,True,True,4,...,Very favorably,Han,No,NaN,Yes,Male,18-29,NaN,High school degree,South Atlantic
9,3.292654e+09,True,True,True,True,True,True,True,True,5,...,Somewhat favorably,Han,No,NaN,No,Male,18-29,"$0 - $24,999",Some college or Associate degree,South Atlantic
10,3.292640e+09,True,False,False,True,False,False,False,False,1,...,Very favorably,I don't understand this question,No,NaN,No,Male,18-29,"$25,000 - $49,999",Some college or Associate degree,Pacific
11,3.292638e+09,True,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,3.292635e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,3.292609e+09,True,False,True,True,True,True,True,True,3,...,Very favorably,Greedo,No,NaN,No,Male,18-29,"$25,000 - $49,999",Bachelor degree,South Atlantic
14,3.292597e+09,True,True,True,True,True,True,True,True,4,...,Very favorably,I don't understand this question,No,NaN,No,Male,30-44,"$50,000 - $99,999",Graduate degree,Mountain
15,3.292587e+09,True,True,True,True,True,True,True,True,4,...,Very favorably,Han,No,NaN,No,Male,18-29,NaN,High school degree,East North Central
16,3.292583e+09,True,True,True,True,True,True,True,True,4,...,Somewhat favorably,Han,Yes,Yes,Yes,Male,18-29,"$0 - $24,999",Some college or Associate degree,West South Central
17,3.292581e+09,True,True,False,False,False,True,False,False,4,...,Very unfavorably,Han,Yes,Yes,No,Male,18-29,"$50,000 - $99,999",Bachelor degree,New England
18,3.292573e+09,True,True,True,True,True,False,False,True,1,...,Very favorably,Greedo,No,NaN,No,Male,18-29,NaN,Some college or Associate degree,Middle Atlantic
19,3.292565e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,Han,No,NaN,No,Male,18-29,NaN,High school degree,South Atlantic
20,3.292562e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,Greedo,No,NaN,Yes,Male,18-29,"$50,000 - $99,999",Some college or Associate degree,West North Central
21,3.292522e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,Han,No,NaN,No,Male,18-29,NaN,Some college or Associate degree,Pacific
22,3.292521e+09,True,False,True,True,True,True,True,False,3,...,Neither favorably nor unfavorably (neutral),I don't understand this question,No,NaN,No,Male,18-29,NaN,Bachelor degree,Pacific
23,3.292512e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,Greedo,Yes,Yes,Yes,Male,18-29,"$50,000 - $99,999",Bachelor degree,South Atlantic
24,3.292483e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,Han,No,NaN,No,Male,18-29,"$0 - $24,999",Bachelor degree,Pacific
25,3.292465e+09,True,True,True,True,True,True,True,True,1,...,Very favorably,Han,No,NaN,No,Male,18-29,NaN,NaN,East North Central
26,3.292448e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,Yes,Male,18-29,"$0 - $24,999",High school degree,East South Central
27,3.292420e+09,True,True,True,True,True,True,True,True,4,...,Very favorably,Greedo,Yes,No,No,Male,18-29,"$100,000 - $149,999",Some college or Associate degree,South Atlantic
28,3.292384e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,Greedo,No,NaN,No,Male,18-29,NaN,Some college or Associate degree,Middle Atlantic
29,3.292380e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,Han,Yes,No,No,Male,18-29,NaN,Some college or Associate degree,Middle Atlantic
30,3.292377e+09,True,True,True,True,True,True,True,True,4,...,Very favorably,Han,Yes,Yes,Yes,Male,18-29,"$150,000+",Some college or Associate degree,East North Central
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1157,3.288426e+09,True,False,True,True,True,True,True,True,3,...,Very favorably,I don't understand this question,No,NaN,No,Female,30-44,"$50,000 - $99,999",Graduate degree,Middle Atlantic
1158,3.288423e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,No,Male,45-60,"$100,000 - $149,999",Graduate degree,Middle Atlantic
1159,3.288423e+09,True,False,False,False,False,False,True,True,2,...,Very favorably,I don't understand this question,No,NaN,No,Female,45-60,"$0 - $24,999",Bachelor degree,Pacific
1160,3.288422e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,No,Female,> 60,"$0 - $24,999",Some college or Associate degree,West South Central
1161,3.288421e+09,True,False,True,False,True,False,False,True,3,...,Very favorably,I don't understand this question,No,NaN,No,Female,18-29,"$25,000 - $49,999",Some college or Associate degree,Pacific
1162,3.288418e+09,True,False,True,True,True,False,True,True,3,...,Neither favorably nor unfavorably (neutral),Greedo,No,NaN,No,NaN,NaN,NaN,NaN,NaN
1163,3.288418e+09,True,True,True,False,False,True,True,True,4,...,Very favorably,I don't understand this question,No,NaN,No,Female,18-29,"$25,000 - $49,999",Graduate degree,South Atlantic
1164,3.288417e+09,True,False,False,False,False,True,True,True,5,...,Very favorably,Han,Yes,No,No,Female,> 60,NaN,Bachelor degree,New England
1165,3.288415e+09,True,False,True,True,True,False,True,True,5,...,Neither favorably nor unfavorably (neutral),Han,No,NaN,No,Male,45-60,"$100,000 - $149,999",Graduate degree,Middle Atlantic
1166,3.288414e+09,True,True,True,True,True,True,True,True,5,...,Very favorably,Greedo,No,NaN,Yes,Female,30-44,"$50,000 - $99,999",Bachelor degree,Mountain
1167,3.288413e+09,True,True,True,True,True,True,True,True,6,...,Very favorably,I don't understand this question,No,NaN,No,Female,18-29,"$150,000+",Some college or Associate degree,South Atlantic
1168,3.288410e+09,True,False,True,False,False,False,True,True,3,...,Very favorably,Greedo,Yes,No,No,Female,30-44,NaN,Graduate degree,East North Central
1169,3.288410e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,No,Female,30-44,"$150,000+",Graduate degree,East North Central
1170,3.288409e+09,True,True,True,False,False,True,True,True,4,...,Very favorably,Han,No,NaN,Yes,Male,45-60,"$25,000 - $49,999",Bachelor degree,South Atlantic
1171,3.288403e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,No,Female,45-60,NaN,Graduate degree,East North Central
1172,3.288403e+09,True,True,True,True,True,True,True,True,6,...,Somewhat unfavorably,Han,Yes,Yes,Yes,Female,> 60,"$25,000 - $49,999",Bachelor degree,Mountain
1173,3.288403e+09,True,True,False,False,False,True,True,True,2,...,Somewhat favorably,Greedo,Yes,No,Yes,Female,> 60,NaN,High school degree,Pacific
1174,3.288403e+09,True,True,True,True,True,True,True,True,5,...,Very favorably,Han,No,NaN,Yes,Female,30-44,NaN,Bachelor degree,Middle Atlantic
1175,3.288402e+09,True,False,True,True,True,False,False,False,1,...,Very favorably,I don't understand this question,No,NaN,Yes,Female,> 60,NaN,Some college or Associate degree,West North Central
1176,3.288401e+09,True,True,True,True,True,True,True,True,1,...,Somewhat favorably,Han,Yes,No,Yes,Female,45-60,"$50,000 - $99,999",Graduate degree,West South Central
1177,3.288398e+09,True,False,True,True,False,False,False,False,2,...,Neither favorably nor unfavorably (neutral),I don't understand this question,No,NaN,No,Female,45-60,"$0 - $24,999",High school degree,Middle Atlantic
1178,3.288396e+09,True,False,True,True,True,False,True,True,1,...,Very favorably,I don't understand this question,No,NaN,Yes,Male,> 60,"$50,000 - $99,999",Some college or Associate degree,Pacific
1179,3.288395e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,No,Female,18-29,NaN,Less than high school degree,West North Central
1180,3.288392e+09,True,True,False,False,False,False,True,True,3,...,Very favorably,Han,No,NaN,Yes,Female,45-60,"$0 - $24,999",Some college or Associate degree,West North Central
1181,3.288390e+09,True,True,True,True,True,True,True,True,3,...,Very favorably,Han,No,NaN,No,Female,45-60,"$0 - $24,999",Some college or Associate degree,Pacific
1182,3.288389e+09,True,True,True,True,True,True,True,True,5,...,Very favorably,Han,No,NaN,Yes,Female,18-29,"$0 - $24,999",Some college or Associate degree,East North Central
1183,3.288379e+09,True,True,True,True,True,True,True,True,4,...,Very favorably,I don't understand this question,No,NaN,Yes,Female,30-44,"$50,000 - $99,999",Bachelor degree,Mountain
1184,3.288375e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,No,Female,30-44,"$50,000 - $99,999",Bachelor degree,Middle Atlantic
1185,3.288373e+09,True,True,True,True,True,True,True,True,4,...,Very favorably,Han,No,NaN,Yes,Female,45-60,"$100,000 - $149,999",Some college or Associate degree,East North Central
1186,3.288373e+09,True,False,True,True,False,False,True,True,6,...,Very unfavorably,I don't understand this question,No,NaN,No,Female,> 60,"$50,000 - $99,999",Graduate degree,Pacific

In [32]:
star_wars[star_wars.columns[9:15]] = star_wars[star_wars.columns[9:15]].astype(float)
star_wars = star_wars.rename(columns={
        "Please rank the Star Wars films in order of preference with 1 being your favorite film in the franchise and 6 being your least favorite film.": "ranking_1",
        "Unnamed: 10": "ranking_2",
        "Unnamed: 11": "ranking_3",
        "Unnamed: 12": "ranking_4",
        "Unnamed: 13": "ranking_5",
        "Unnamed: 14": "ranking_6"
        })
star_wars.head()

,RespondentID,Have you seen any of the 6 films in the Star Wars franchise?,Do you consider yourself to be a fan of the Star Wars film franchise?,seen_1,seen_2,seen_3,seen_4,seen_5,seen_6,ranking_1,...,Unnamed: 28,Which character shot first?,Are you familiar with the Expanded Universe?,Do you consider yourself to be a fan of the Expanded Universe?ÂÃ¦,Do you consider yourself to be a fan of the Star Trek franchise?,Gender,Age,Household Income,Education,Location (Census Region)
1,3.292880e+09,True,True,True,True,True,True,True,True,3.0,...,Very favorably,I don't understand this question,Yes,No,No,Male,18-29,NaN,High school degree,South Atlantic
2,3.292880e+09,False,NaN,False,False,False,False,False,False,NaN,...,NaN,NaN,NaN,NaN,Yes,Male,18-29,"$0 - $24,999",Bachelor degree,West South Central
3,3.292765e+09,True,False,True,True,True,False,False,False,1.0,...,Unfamiliar (N/A),I don't understand this question,No,NaN,No,Male,18-29,"$0 - $24,999",High school degree,West North Central
4,3.292763e+09,True,True,True,True,True,True,True,True,5.0,...,Very favorably,I don't understand this question,No,NaN,Yes,Male,18-29,"$100,000 - $149,999",Some college or Associate degree,West North Central
5,3.292731e+09,True,True,True,True,True,True,True,True,5.0,...,Somewhat favorably,Greedo,Yes,No,No,Male,18-29,"$100,000 - $149,999",Some college or Associate degree,West North Central